version: '2'
services:
    kafka:
      image: wurstmeister/kafka:1.1.0
      environment:
        KAFKA_LOG_MESSAGE_FORMAT_VERSION: "0.10.2"
        KAFKA_LISTENERS: "PLAINTEXT://:9092,SSL://:9093,SASL_PLAINTEXT://:9094"
        KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${KAFKA_ADVERTISED_HOST_NAME}:9092,SSL://${KAFKA_ADVERTISED_HOST_NAME}:9093,SASL_PLAINTEXT://${KAFKA_ADVERTISED_HOST_NAME}:9094"
        KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
        KAFKA_SECURITY_INTER_BROKER_PROTOCOL: "PLAINTEXT"
        KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
        KAFKA_SUPER_USERS: "User:admin,User:broker"
        KAFKA_OPTS: "-Djava.security.auth.login.config=/var/private/sasl/sasl.conf"
      volumes:
        - ./docker/start-kafka.sh:/usr/bin/start-kafka.sh

